config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    patch :change_status, on: :member
    patch :update_to_today, on: :member
    patch :not_to_today, on: :member
    patch :update_to_tomorrow, on: :member
  end

  get '/affirmations', to: 'static#affirmations'

  devise_for :users

  resources :todo_items
  resources :journal_items
  
  devise_scope :user do
    get 'users/account', to: 'users/registrations#account', as: :user_account
  end

  # Defines the root path route ("/")
  root "todos#index"
 # root "home#index"
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_item, only: %i[ show edit update destroy ]

  layout 'app' 

  # GET /todo_items or /todo_items.json
  def index
    @todo_items = TodoItem.all
  end

  # GET /todo_items/1 or /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items or /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.turbo_stream
        format.html { redirect_to todo_item_url(@todo_item), notice: "Todo item was successfully created." }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo_item)}_form", partial: "form", locals: { todo_item: @todo_item }) }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1 or /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.turbo_stream
        format.html { redirect_to todo_item_url(@todo_item), notice: "Todo item was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo_item)}_form", partial: "form", locals: { todo_item: @todo_item})}
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1 or /todo_items/1.json
  def destroy
    @todo_item.destroy

    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: "Todo item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :body, :competed)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_with(model: todo_item, id: "#{dom_id(todo_item)}_form", class: "") do |form| %>
  <% if todo_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
        <% todo_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :competed %>
    <%= form.check_box :competed, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div id="<%= dom_id todo_item %>" class="flex gap-8 justify-between p-4 ring-1 ring-[#E2D3BE] rounded-2xl ">
  <div>
    <div class="flex gap-2">

  <p class="">
  <input type="checkbox" />
    <%#= todo_item.competed %>
  </p>
  <p class="">
    <%= todo_item.title %>
  </p>
    </div>

  <p class="">
    <%= todo_item.body %>
  </p>

  </div>

  <% if action_name != "show" %>
    <div>
    <%#= link_to "Show", todo_item, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit', edit_todo_item_path(todo_item), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  <% end %>
</div>

app/views/todo_items/create.turbo_stream.erb
<%= turbo_stream.prepend "todo_item" do %>
  <%= render "todo_item", todo_item: @todo_item %>
<% end %>

<%= turbo_stream.replace "#{dom_id(TodoItem.new)}_form" do %>
  <%= render "form", todo_item: TodoItem.new %>
<% end %>

app/views/todo_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing todo item</h1>

  <%= render "form", todo_item: @todo_item %>

  <%= link_to "Show this todo item", @todo_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to todo items", todo_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todo_items/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>


  <h1 class="font-bold text-4xl">Todo items</h1>

  <div>
    <%= render "form", todo_item: TodoItem.new %>
  </div>

  <div id="todo_items" class="min-w-full">
    <%= render @todo_items %>
  </div>
</div>

app/views/todo_items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo item</h1>

  <%= render "form", todo_item: @todo_item %>

  <%= link_to 'Back to todo items', todo_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todo_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @todo_item %>

    <%= link_to 'Edit this todo_item', edit_todo_item_path(@todo_item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this todo_item', todo_item_path(@todo_item), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to todo_items', todo_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>