config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    patch :change_status, on: :member
    patch :update_to_today, on: :member
    patch :not_to_today, on: :member
    patch :update_to_tomorrow, on: :member
  end

  get '/affirmations', to: 'static#affirmations'

  devise_for :users

  resources :todo_items
  resources :journal_items
  
  devise_scope :user do
    get 'users/account', to: 'users/registrations#account', as: :user_account
  end

  # Defines the root path route ("/")
  root "todos#index"
 # root "home#index"
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum status: {
    incomplete: 0,
    complete: 1
  }

  scope :sorted_by_due_date, -> {
    order(Arel.sql("CASE WHEN due_date IS NULL THEN 1 ELSE 0 END, due_date ASC"))
  }
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy change_status update_to_today update_to_tomorrow ]

  layout 'app' 

  # GET /todos or /todos.json
  def index
    @todos = Todo.where(status: params[:status].presence || 'incomplete').sorted_by_due_date

    @today_todos = Todo.where(due_date: Date.today, status: Todo.statuses[:incomplete])

    @all_not_today = Todo.where(status: params[:status].presence || 'incomplete')
      .where("due_date IS NULL OR due_date != ?", Date.today)
      .sorted_by_due_date
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: "Todo was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        
        format.html { redirect_to todos_path, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_status
    old_status = @todo.status

    @todo.update(status: todo_params[:status])

    respond_to do |format|
      if old_status == 'incomplete' && @todo.complete?
        format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_container") }
        format.html { redirect_back(fallback_location: todos_path, notice: "Updated todo status.") }
      else
        format.html { redirect_back(fallback_location: todos_path, notice: "Updated todo status.") }
      end
    end
  end

  def update_to_today
    @todo.update(due_date: Date.today)
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_container") }
      format.html { redirect_back(fallback_location: todos_path, notice: "Updated todo status.") }
    end
  end

def update_to_tomorrow
  @todo = Todo.find(params[:id])
  
  tomorrow = Time.zone.tomorrow.to_date
  @todo.update(due_date: tomorrow)
  
  respond_to do |format|
    format.html { redirect_to todos_path, notice: "Updated todo status." }
  end
end

  def not_to_today
    @todo = Todo.find(params[:id])
    @todo.update(due_date: nil)
    respond_to do |format|
      format.html { redirect_to todos_path, notice: "Updated todo status." }
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_container") }
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_params
    params.require(:todo).permit(:title, :description, :status, :due_date)
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_current_todo.html.erb
<div id="<%= "#{dom_id(todo)}_container" %>">

  <div class="flex rounded-3xl overflow-hidden relative ring-1 ring-black/5 bg-white">
    <div class="flex w-full">
      <div class="p-6 flex-1">

        <%= link_to  edit_todo_path(todo), class: "text-2xl hover:opacity-70 transition-all duration-200" do %>
          <%= todo.title %>
          <p class="text-xl opacity-70 leading-tight"><%= todo.description  %></p>
        <% end %>
        <div class="mt-6 flex gap-2">

          <% if todo.due_date.present? %>
            <%= button_to "Someday", not_to_today_todo_path(todo), method: :patch, remote: true, class: "px-6 py-2 duration-200 transition-all bg-zinc-300/20 hover:bg-zinc-300/50 rounded-full text-base" %>
            <%= button_to "Tomorrow", update_to_tomorrow_todo_path(todo), method: :patch, remote: true, class: "px-6 py-2 duration-200 transition-all bg-zinc-300/20 hover:bg-zinc-300/50 rounded-full text-base" %>
          <% end %>

        </div>
      </div>
    </div>
    <div class="flex items-center border-l duration-100 transition-all border-black/5 justify-center hover:bg-[#427A74] text-[#427A74] px-16 hover:text-white relative">
      <%= button_to "Done", change_status_todo_path(todo, todo: { status: 'complete' }), class: "absolute inset-0  font-medium ", method: :patch %>
    </div>
  </div>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, id: "#{dom_id(todo)}_form", class: "")  do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-6">
    <%= form.label :title, class: "sr-only" %>
    <%= form.text_area :title, placeholder: "Notes", rows: 4,  autofocus: true, placeholder: "Title", class: "placeholer:text-zinc-400 border-0 rounded-md w-full p-0 focus:ring-0 focus:border-0 ring-0 bg-transparent text-3xl focus:outline-none  " %>
  </div>

  <div class="hidden">
    <%= form.label :description, class: "sr-only" %>
    <%= form.text_area :description, placeholder: "Notes", rows: 4, class: "placeholer:text-zinc-400 border-0 text-2xl rounded-md w-full p-0 focus:ring-0 focus:border-0 ring-0 bg-transparent focus:outline-none  " %>
  </div>

  <div class="text-2xl mb-6">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "mt-0 text-2xl px-0.5 bg-transparent border-0 ring-0 focus:ring-0 placeholer:text-zinc-400" %>
  </div>

  <div class="flex items-center justify-between">

    <div class="mt-2 flex gap-4 w-full">

      <%= form.submit class: "rounded-full text-2xl text-white flex-1 hover:bg-orange-600 cursor-pointer font-medium bg-orange-500 px-8 py-4 duration-200 transition-all" %>

      <% if action_name == "edit" %>
        <%= button_to todo_path(todo), class: "rounded-full inline-block text-2xl  font-medium hover:bg-rose-600  bg-rose-500 text-white px-12 duration-200 transition-all py-4 text-center", method: :delete do %>
Delete
        <% end %>
      <% end %>
    </div>

  </div>

      <%= link_to "Close", todos_path, class: "rounded-full inline-block text-2xl mt-4 font-medium hover:opacity-60 w-full ring-2 ring-[#EADED0] px-8 py-3 text-center" %>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= "#{dom_id(todo)}_container" %>">

  <div class="flex p-5 rounded-3xl bg-white ring-1 ring-black/5 relative justify-between items-start">
    <% if todo.complete? %>
      <%= button_to change_status_todo_path(todo, todo: { status: 'incomplete' }), class: "bg-green-600 px-4 py-2 rounded hover:bg-green-700", method: :patch do %>
        <span class="sr-only">Mark as incomplete</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
        </svg>
      <% end %>


      <%= link_to todo.title, edit_todo_path(todo), class: todo.complete? ? 'line-through' : '' %>

      <p><%= todo.description  %></p>

    <% else %>


      <div class="flex flex-col gap-0 w-full">
        <%= link_to  edit_todo_path(todo), class: "hover:opacity-80 transition-all duration-200 text-xl" do %>

            <% if todo.due_date.present?  %>
              <p class="text-base mb-2"><%= todo.due_date.strftime('%B %e')  %></p>
              <% end %>
          <%= todo.title %>
          <p class="opacity-70 leading-tight"><%= todo.description  %></p>
        <% end %>

        <div class='flex gap-2 justify-between mt-4  w-full'>

          <%= button_to change_status_todo_path(todo, todo: { status: 'complete' }), class: "ring-1 ring-[#427A74]/30 hover:ring-[#427A74] text-[#427A74] transition-all duration-300 hover:bg-[#427A74] rounded-full text-base px-8 hover:text-white py-1.5 text-medium inline-block ", method: :patch do %>
            <span class="sr-only">Mark as complete</span>
            <div>Done</div>
          <% end %>

          <div class="flex gap-2">

            <% if todo.due_date.present? || todo.due_date.nil? %>

              <% unless todo.due_date == Date.current %>
                <%= button_to "Today", update_to_today_todo_path(todo), method: :patch, remote: true, class: "btn-link px-6 py-2 duration-200 transition-all bg-zinc-300/20 hover:bg-zinc-300/50 rounded-full text-base" %>
              <% end %>

              <%= button_to "Tomorrow", update_to_tomorrow_todo_path(todo), method: :patch, remote: true, class: "btn-link px-6 py-2 duration-200 transition-all bg-zinc-300/20 hover:bg-zinc-300/50 rounded-full text-base" %>
            <% end %>

          </div>

        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/todos/edit.html.erb
<div class="max-w-2xl pt-20 mx-auto">
  <%= render "form", todo: @todo %>
</div>

app/views/todos/index.html.erb
<% content_for(:nav) do %>
  <div class="flex bg-[#EDE3D4] text-lg px-1 py-1 rounded-full gap-1">

    <%= link_to "Today", todos_path, class: "#{params[:status] != 'complete' ? 'bg-[#FAF4EC]' : 'bg-[#EDE3D4]'} flex-1 px-8 rounded-full py-2" %>
    <%= link_to "Active",
    todos_path(status: "incomplete"),
    class: "#{params[:status] == 'complete' ? 'bg-[#FAF4EC]' : 'bg-[#EDE3D4]'} flex-1 px-8 rounded-full py-2" %>
  <%= link_to "Complete",
    todos_path(status: "complete"),
    class: "#{params[:status] == 'complete' ? 'bg-[#FAF4EC]' : 'bg-[#EDE3D4]'} flex-1 px-8 rounded-full py-2" %>
  </div>
<% end %>

<div class="flex pb-32 flex-col mx-auto max-w-3xl gap-12">
  <% unless params[:status] == "complete" %>
    <div class="">
      <% if @today_todos.any? %>
        <h2 data-current-date-target="date" data-controller="current-date" class="text-2xl mb-4">
        </h2>
        <div class="flex flex-col mb-12 gap-4">
          <%= render partial: "current_todo", collection: @today_todos, as: :todo %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="">
    <h2 class="text-2xl mb-4">All Tasks</h2>
    <div id="todos" class="flex flex-1 flex-col gap-2">
      <%= render @all_not_today %>
    </div>
  </div>

</div>


<%= link_to "New Task", new_todo_path, class: "hover:bg-orange-600 transition-all duration-300 px-24 fixed bottom-8 left-1/2 -translate-x-1/2 bg-orange-500 text-2xl text-white font-medium rounded-full text-center py-3 " %>

app/views/todos/new.html.erb
<div class="max-w-4xl pt-20 mx-auto">
  <%= render "form", todo: @todo %>
</div>

app/views/todos/show.html.erb
<%= render @todo %>

<div class="flex justify-between">
  <%= link_to 'Back', todos_path, class: " rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= button_to todo_path(@todo), class: "bg-red-600 px-4 py-2 rounded hover:bg-red-700", method: :delete do %>
    <span class="sr-only">Delete</span>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor" title="Delete todo">
      <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
    </svg>
  <% end %>
</div>