config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    patch :change_status, on: :member
    patch :update_to_today, on: :member
    patch :not_to_today, on: :member
    patch :update_to_tomorrow, on: :member
  end

  get '/affirmations', to: 'static#affirmations'

  devise_for :users

  resources :todo_items
  resources :journal_items
  
  devise_scope :user do
    get 'users/account', to: 'users/registrations#account', as: :user_account
  end

  # Defines the root path route ("/")
  root "todos#index"
 # root "home#index"
end

app/models/journal_item.rb
class JournalItem < ApplicationRecord
  has_many_attached :pictures
  acts_as_taggable_on :tags

  scope :search, ->(query) {
    return if query.blank?
    where(arel_table[:body].matches("%#{query}%"))
  }

  def pictures_as_thumbnail(pic)
    pic.variant(resize_to_limit: [800, 800]).processed
  end
end

app/controllers/journal_items_controller.rb
class JournalItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_journal_item, only: %i[ show edit update destroy ]

  layout 'app' 

  # GET /journal_items or /journal_items.json
  def index
    @pagy, @journal_items = pagy JournalItem.order("published_at DESC NULLS LAST")

if params[:month].present?
    selected_month = params[:month].to_i
    @journal_items = @journal_items.where("EXTRACT(MONTH FROM published_at ) = ?", selected_month)
@current_month_name = Date::MONTHNAMES[selected_month]
  elsif Time.now
    current_month = Time.now.month
    @journal_items = @journal_items.where("EXTRACT(MONTH FROM published_at ) = ?", current_month)
@current_month_name = Date::MONTHNAMES[current_month]
  end
  end

  # GET /journal_items/1 or /journal_items/1.json
  def show
  end

  # GET /journal_items/new
  def new
    @journal_item = JournalItem.new
    render layout: "layouts/full"
  end

  # GET /journal_items/1/edit
  def edit
  end

  # POST /journal_items or /journal_items.json
  def create
    @journal_item = JournalItem.new(journal_item_params)

    respond_to do |format|
      if @journal_item.save
        format.html { redirect_to journal_items_path, notice: "Journal item was successfully created." }
#        format.html { redirect_to journal_item_url(@journal_item), notice: "Journal item was successfully created." }
        format.json { render :show, status: :created, location: @journal_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journal_items/1 or /journal_items/1.json
  def update
    respond_to do |format|
      if @journal_item.update(journal_item_params)
        format.html { redirect_to journal_items_path, notice: "Journal item was successfully updated." }
        format.json { render :show, status: :ok, location: @journal_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journal_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journal_items/1 or /journal_items/1.json
  def destroy
    @journal_item.destroy

    respond_to do |format|
      format.html { redirect_to journal_items_url, notice: "Journal item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_item
      @journal_item = JournalItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_item_params
      params.require(:journal_item).permit(:body, :published_at, :title, pictures: [])
    end
end

app/helpers/journal_items_helper.rb
module JournalItemsHelper
end

app/views/journal_items/_form.html.erb
<%= form_with(model: journal_item, class: "bg-white p-8 rounded-3xl") do |form| %>
  <% if journal_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(journal_item.errors.count, "error") %> prohibited this journal_item from being saved:</h2>

      <ul>
        <% journal_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex justify-between">
  <div class="flex items-center focus:border-0 outline-none gap-0">
<svg class="w-6 h-6" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path opacity="0.2" d="M27 6V11H5V6C5 5.73478 5.10536 5.48043 5.29289 5.29289C5.48043 5.10536 5.73478 5 6 5H26C26.2652 5 26.5196 5.10536 26.7071 5.29289C26.8946 5.48043 27 5.73478 27 6Z" fill="black"/>
<path d="M26 4H23V3C23 2.73478 22.8946 2.48043 22.7071 2.29289C22.5196 2.10536 22.2652 2 22 2C21.7348 2 21.4804 2.10536 21.2929 2.29289C21.1054 2.48043 21 2.73478 21 3V4H11V3C11 2.73478 10.8946 2.48043 10.7071 2.29289C10.5196 2.10536 10.2652 2 10 2C9.73478 2 9.48043 2.10536 9.29289 2.29289C9.10536 2.48043 9 2.73478 9 3V4H6C5.46957 4 4.96086 4.21071 4.58579 4.58579C4.21071 4.96086 4 5.46957 4 6V26C4 26.5304 4.21071 27.0391 4.58579 27.4142C4.96086 27.7893 5.46957 28 6 28H26C26.5304 28 27.0391 27.7893 27.4142 27.4142C27.7893 27.0391 28 26.5304 28 26V6C28 5.46957 27.7893 4.96086 27.4142 4.58579C27.0391 4.21071 26.5304 4 26 4ZM9 6V7C9 7.26522 9.10536 7.51957 9.29289 7.70711C9.48043 7.89464 9.73478 8 10 8C10.2652 8 10.5196 7.89464 10.7071 7.70711C10.8946 7.51957 11 7.26522 11 7V6H21V7C21 7.26522 21.1054 7.51957 21.2929 7.70711C21.4804 7.89464 21.7348 8 22 8C22.2652 8 22.5196 7.89464 22.7071 7.70711C22.8946 7.51957 23 7.26522 23 7V6H26V10H6V6H9ZM26 26H6V12H26V26Z" fill="black"/>
</svg>
    <%= form.date_field :published_at, class: "border-0 focus:ring-0 text-slate-800  text-slate-400" %>
  </div>


  </div>

  <div class="w-full p-8 bg-purple-50 rounded-xl mt-6">
    <%= form.file_field :pictures, multiple: true %>
  </div>

  <div class="flex flex-col gap-1 mt-3">
    <%= form.text_field :title, placeholder: "You could add a title", class: "text-xl font-bold  outline-none border-0 focus:bg-slate-50 py-3 focus:ring-0 rounded-xl placeholder:text-slate-400" %>
  </div>
  <div class="flex flex-col gap-1 mt-2">
    <%= form.text_area :body, rows: 4, placeholder: 'Memory', class: "text-4xl font-light leading-tight font-serif outline-none border-0 focus:bg-slate-50 py-3 focus:ring-0 rounded-xl placeholder:text-slate-400" %>
  </div>

  <div class="flex justify-between mt-8 gap-8">
    <%= link_to raw('&larr; Back'), journal_items_path, class: "py-4 px-5 hover:text-purple-500 durateion-300 transition-all font-medium" %>
<%= form.submit(action_name == "edit" ? "Update" : "Create", class: "rounded-xl py-4 px-8 bg-purple-500 hover:bg-purple-600 transition-all duration-300 text-white inline-flex font-medium cursor-pointer") %>
  </div>
<% end %>

app/views/journal_items/_journal_item.html.erb
<div id="<%= dom_id journal_item %>" class="w-full  transition-all duration-300 rounded-2xl">

  <% unless journal_item.pictures.empty? %>
    <% if journal_item.pictures.count == 1 %>

      <div class="flex w-full flex-col items-center justify-center self-start gap-4 ">
        <% journal_item.pictures.each_with_index do |picture, index| %>
          <%= link_to picture do %>
            <%= image_tag journal_item.pictures_as_thumbnail(picture), class: "hover:scale-100 transition-all duration-300 -mt-8 shrink-0 #{index.odd? ? 'rotate-6' : '-rotate-2'}" %>
          <% end %>
        <% end %>
      </div>

      <div class="flex gap-8 mt-12 justify-between items-start w-full p-8 pt-0 ">
        <div class="flex-1">
          <h3 class="text-3xl font-semibold my-5">
            <%= journal_item.title %>
          </h3>

          <p class="my-5 text-2xl">
          <%= journal_item.body %>
          </p>

          <%= render "journal_item_actions", journal_item: journal_item %>
        </div>

      </div>

    <% else %>

      <div class="flex w-full mt-20 flex-col items-center justify-center self-start gap-4 ">
        <% journal_item.pictures.each_with_index do |picture, index| %>
          <div class="sticky top-8">
            <%= image_tag journal_item.pictures_as_thumbnail(picture), class: "hover:scale-100 transition-all duration-300  -mt-8 shrink-0 #{index.odd? ? 'rotate-6' : '-rotate-6'}" %>
          </div>
        <% end %>
      </div>

      <div class="flex gap-8 mt-12 justify-between items-start w-full">
        <div class="flex-1">
        <h3 class="text-2xl font-serif font-semibold mb-5">
          <%= journal_item.title %>
        </h3>

        <p class="text-4xl font-light leading-tight font-serif">
        <%= journal_item.body %>
        </p>

          <%= render "journal_item_actions", journal_item: journal_item %>
        </div>

      </div>
    <% end %>
  <% else %>

    <div class="flex gap-4 justify-between w-full flex-col">
      <div class="max-w-2xl w-full">
        <h3 class="text-xl font-bold mb-5">
          <%= journal_item.title %>
        </h3>

        <p class="text-4xl font-light leading-tight font-serif ">
        <%= journal_item.body %>
        </p>
      </div>

      <%= render "journal_item_actions", journal_item: journal_item %>
    </div>

  <% end %>


</div>

app/views/journal_items/edit.html.erb
<div class="mx-auto max-w-4xl">

  <div class="flex mb-6 justify-between items-center">
    <h1 class="font-bold font-serif text-2xl">Edit</h1>

    <%= button_to journal_item_path(@journal_item), method: :delete, class: "text-slate-600 hover:text-rose-500 p-3", data: { turbo_method: :delte, turbo_confirm: 'Are you sure?' } do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="w-7 h-7" fill="currentColor" viewBox="0 0 256 256"><path d="M200,56V208a8,8,0,0,1-8,8H64a8,8,0,0,1-8-8V56Z" opacity="0.2"></path><path d="M216,48H176V40a24,24,0,0,0-24-24H104A24,24,0,0,0,80,40v8H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM96,40a8,8,0,0,1,8-8h48a8,8,0,0,1,8,8v8H96Zm96,168H64V64H192ZM112,104v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm48,0v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Z"></path></svg>
    <% end %>
  </div>

  <%= render "form", journal_item: @journal_item %>

</div>

app/views/journal_items/index.html.erb
<div class="hidden">
  <% I18n.t("date.month_names").compact.each_with_index do |month, index| %>
    <%= link_to month, journal_items_path(month: index + 1), class: "text-base hover:text-purple-500" %>
  <% end %>

  <% unless params[:month].blank? || params[:month].to_i == Date.today.month %>
    <%= link_to "Today", journal_items_path, class: "text-lg bg-purple-200 fixed bottom-8 right-8 w-fit self-end px-8 py-1.5 mt-8 text-purple-500 rounded-full hover:text-purple-700" %>
  <% end %>
</div>

<div class="max-w-4xl pt-8 mx-auto pb-40">

  <% if @journal_items.empty? %>
    <p class="grid place-items-center h-full">Add memory about your or your beautiful family</p>
  <% else %>
    <div id="journal_items" class="w-full flex flex-col gap-20">
      <%= render @journal_items %>
    </div>
  <% end %>

  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

<%= link_to "New Moment", new_journal_item_path, class: "hover:bg-orange-600 transition-all duration-300 px-16 fixed bottom-8 left-1/2 -translate-x-1/2 bg-orange-500 text-white font-medium rounded-full text-center py-3 " %>

app/views/journal_items/new.html.erb
<div class="mx-auto max-w-4xl">
  <h1 class="font-bold mb-12 text-2xl">Write new memory</h1>

  <%= render "form", journal_item: @journal_item %>

</div>

app/views/journal_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @journal_item %>

    <div class="flex justify-between gap-2">
      <div class="flex gap-2">
    <%= link_to raw('&larr;'), journal_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit', edit_journal_item_path(@journal_item), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </div>

      <%= button_to 'Destroy', journal_item_path(@journal_item), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
  </div>
</div>