config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    patch :change_status, on: :member
    patch :update_to_today, on: :member
    patch :not_to_today, on: :member
    patch :update_to_tomorrow, on: :member
  end

  get '/affirmations', to: 'static#affirmations'

  devise_for :users

  resources :todo_items
  resources :journal_items
  
  devise_scope :user do
    get 'users/account', to: 'users/registrations#account', as: :user_account
  end

  # Defines the root path route ("/")
  root "todos#index"
 # root "home#index"
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(template: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/app.html.erb
<main class="px-4 sm:px-6 sm:py-3 lg:px-10 py-5">

    <div class="mb-8 items-center flex justify-between">
        <%= link_to "Kidsy", todos_path %>
        <%= yield :nav %>
        <div></div>
    </div>

    <%= render "layouts/nav/main_nav" %>
    <%= yield %>
</main>

<% parent_layout "base" %>

app/views/layouts/application.html.erb
<%= yield %>

<% parent_layout "base" %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kidsy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[#FAF4EC] text-xl text-zinc-800 overflow-y-scroll">
    <p class="notice"><%#= notice %></p>
    <p class="alert"><%#= alert %></p>
    <%= yield %>

    <%= turbo_frame_tag :modal %>

<% if Rails.env.development? %>
  <div class="fixed bottom-1 left-1 z-50  flex h-10 w-10 items-center justify-center rounded-full bg-red-500 p-3 text-xs font-mono text-white">
    <div class="block sm:hidden">xs</div>
    <div class="hidden sm:block md:hidden lg:hidden xl:hidden 2xl:hidden">sm</div>
    <div class="hidden md:block lg:hidden xl:hidden 2xl:hidden">md</div>
    <div class="hidden lg:block xl:hidden 2xl:hidden">lg</div>
    <div class="hidden xl:block 2xl:hidden">xl</div>
    <div class="hidden 2xl:block">2xl</div>
  </div>
<% end %>
  </body>
</html>

app/views/layouts/full.html.erb
<main class="p-12">
  <%= yield %>
</main>

<% parent_layout "base" %>